gitops-runtime:
  global:
    codefresh:
      accountId: 6733cdbfd09d4b15be739648
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
